# Generated by Django 5.0 on 2024-01-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_alter_book_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pdetails',
            new_name='bdetails',
        ),
    ]
