# Generated by Django 5.0 on 2024-01-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_rename_pdetails_book_bdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bdetails',
            field=models.CharField(max_length=1000, verbose_name='Book Details'),
        ),
    ]
