# Generated by Django 5.0 on 2024-01-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0006_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
