# Generated by Django 5.0 on 2024-01-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0009_cart_qty_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Customer Name')),
                ('email', models.CharField(default='', max_length=70, verbose_name='Customer Email')),
                ('phone', models.CharField(default='', max_length=70, verbose_name='Customer No.')),
                ('desc', models.CharField(default='', max_length=700, verbose_name='Customer Query')),
            ],
        ),
    ]
